### ISSUE TITLE
Fastwalk should traverse directory symlinks and return all their contents

### ISSUE THREAD

**Issue by maximbaz** [mattn/go-zglob#11]
Consider the following directory structure:

```
/root/
    symlink1   --> folder1
    folder1/
        file1
```

### Current behavior

Currently, the code `zglob.Glob("/root/**/*")` traverses the following entries via fastwalk:

```
/root
/root/symlink1
/root/folder1
/root/folder1/file1
```

And thus there is only one result of the `Glob`: `/root/folder1/file1`

### Expected behavior

What I would expect instead is to get is the following traversal:

```
/root
/root/symlink1
/root/symlink1/file1   <-----------------------------
/root/folder1
/root/folder1/file1
```

And thus I would expect `Glob` to return two results: `/root/folder1/file1` and `/root/symlink1/file1`

### Scenario

We use this library over at [browserpass](https://github.com/dannyvankooten/browserpass/). Specifically, we `Glob` all `**/*.gpg` files and display them in a list. 

Generally with `pass`, the users are encouraged to create directory symlinks in case passwords are shared among several domains, because that is how we could prevent the fishing attacks.

However, due to this bug the symlinked folders are not being traversed, and we cannot prevent the fishing attacks.

Our tracking issue: https://github.com/dannyvankooten/browserpass/issues/85

**Comment by mattn** [comment]
https://github.com/mattn/go-zglob/pull/12 fixes this issue?

**Comment by mattn** [comment]
Ah, you expect both entry.

**Comment by maximbaz** [comment]
Precisely, I expect two entries, in my example `/root/folder1/file1` and `/root/symlink1/file1`. 
Thanks for looking into this 🙂

**Comment by mattn** [comment]
Hmm, I'm thinking this become breaking compatibility. So better way to fix will be add new method that traverse symlinks.

**Comment by maximbaz** [comment]
Or a boolean parameter maybe - both options are fine for me!

**Comment by maximbaz** [comment]
Hey @mattn, I've received a few more requests from users requesting this feature, so I wanted to send out a friendly ping to you 🙂 Have you had a chance to think more about this?

**Comment by mattn** [comment]
This is possibly recursibly loop. So It should be carefuly implemented. What API is best do you think?

**Comment by maximbaz** [comment]
This is a possibility, you are right. But since this is a rather specific use-case, maybe at least in the first iteration this case should be ignored? Just want to get something out 😃 

I like the API of the existing `zglob.Glob`, ideally the new function would be very similar in terms of how I call it and how it returns results.
