### ISSUE TITLE
Bug - tests fail with multiple directories

### ISSUE THREAD

**Issue by apropostech** [mattn/go-zglob#15]
There seems to be a bug in that `*oo/**/*.txt` fails matching multiple directories in the `/**/` expression, e.g. running tests with the following expression {`*oo/**/*.txt`, []string{`foo/bar/baz.txt`, `foo/bar/baz/noo.txt`, `foo/bar/baz/foo/noo.txt`}, nil} fails.

Issue prevents implementation of subdirectory search in browserpass (https://github.com/dannyvankooten/browserpass/pull/196).

**Comment by mattn** [comment]
```
$ find .
.
./foo
./foo/bar
./foo/bar/baz
./foo/bar/baz/foo
./foo/bar/baz/foo/noo.txt
./foo/bar/baz.txt
./foo/bar/noo.txt

$ zglob '*foo/**/*.txt&
foo/bar/baz/foo/noo.txt
foo/bar/baz.txt
foo/bar/noo.txt
```
It seems working intended. Could you please explain how to reproduce?

**Comment by apropostech** [comment]
I modified zglob_test.go to figure out what was going on but realise now there were some issues with my modification.

The underlying issue though is that the following pattern doesn't match as expected `zglob.GlobFollowSymlinks(s.path + "/**/" + query + "*/**/*")`.

It gives 0 results for the paths `abc.org/wiki/user4`, `"abc.org/wiki/work/user5"` when querying for `wiki` or `work`. First level `abc.org` works as expected.

**Comment by maximbaz** [comment]
@mattn here's another example of what we are trying to achieve:

```
❯ find .
.
./zglob
./one
./one/two
./one/two/three
./one/two/three/four
./one/two/three/four/five
./one/two/three/four/five/file.txt

❯ ./zglob '**/five/*.txt'
one/two/three/four/five/file.txt

❯ ./zglob '**/five/**/*.txt'

❯ ./zglob '**/four/**/*.txt'
```

Expected result: all three `zglob` commands find the same file.

**Comment by mattn** [comment]
Current implementation, `**` should have 1 element at least.

**Comment by maximbaz** [comment]
OK, but shouldn't then at least the last example work too?

**Comment by mattn** [comment]
Could you please try this patch?

```diff
diff --git a/zglob.go b/zglob.go
index 33296e2..3a7d71e 100644
--- a/zglob.go
+++ b/zglob.go
@@ -73,7 +73,9 @@ func makePattern(pattern string) (*zenv, error) {
 		if cc[i] == '*' {
 			if i < len(cc)-2 && cc[i+1] == '*' && cc[i+2] == '/' {
 				filemask += "(.*/)?"
-				dirmask = filemask
+				if dirmask == "" {
+					dirmask = filemask
+				}
 				i += 2
 			} else {
 				filemask += "[^/]*"
```

**Comment by maximbaz** [comment]
It works, solves all three cases!
