### ISSUE TITLE
Feature request: Allow specification of the root directory

### ISSUE THREAD

**Issue by troykinsella** [mattn/go-zglob#2]
Allow a root directory to be passed into Glob(). This library is useless to me without that control.

**Comment by mattn** [comment]
Please explain your expected.

**Comment by troykinsella** [comment]
After examining several other Go glob implementations, and discovering further how `Glob()` is intended to be used, I realized accepting only a glob string in `Glob()` is pretty standard, so I retract my hasty "useless" comment. Sorry.

But, to explain what I was thinking, I wanted to be able to glob matches, say, `**/something` relatively to a base directory that is not necessarily the CWD. Of course, I realized I just have to concatenate a base directory and a relative glob before passing it into `Glob()`. So, I suppose you can close this feature request.

Thanks for the library!

**Comment by mattn** [comment]
Then you can do `zglob.Glob(filepath.Join(base, "**/something")`.

**Comment by lrstanley** [comment]
Believe this can be closed now.
