### ISSUE TITLE
Add glob negation support

### ISSUE THREAD

**Issue by andreynering** [mattn/go-zglob#26]
Hi @mattn, thanks a lot for maintaining this lib! I've being using it for a long time and it's pretty stable and fast!

Negation would allow to exclude a given patten from the returned files.

For example, this would return all `.go` files, but not those living in the `vendor/` directory:

```
./!(vendor)/**/*.go
```

**Comment by mattn** [comment]
Fixed in last change.

**Comment by marco-m** [comment]
thanks! :-)
