### ISSUE TITLE
Windows paths

### ISSUE THREAD

**Issue by cugu** [mattn/go-zglob#27]
The following does not create any results
``` go
zglob.Glob(`D:\**\*.log`)
```

while
``` go
zglob.Glob(`D:\subdir\**\*.log`)
```
does.

**Comment by zetamatta** [comment]
I found that `fastwalk.FastWalk` stops immediately when `ioutil.ReadDir` returns an error.

And the root directory often has the directory that `ioutil.ReadDir` can not read and returns 
the error like `Access is denied.` . 

When I try `zglob.Glob("C:\\**\\*.log")` , `open C:\\Config.Msi: Access is denied.` occures.

**Comment by mattn** [comment]
Closable?
