### ISSUE TITLE
Does not support symlinks

### ISSUE THREAD

**Issue by eterps** [mattn/go-zglob#3]
Couldn't figure out what was going on, but as soon as I made a symlink pointing to what previously has been a directory all of a sudden the [browserpass](https://github.com/dannyvankooten/browserpass) chrome extension stopped working (which uses go-zglob). Hopefully support for symlinks can be added in the future, for now maybe a good idea to mention it in the README to warn people that existing code can break when they use symbolic links.

**Comment by mattn** [comment]
I'll try to replace filepath.Walk to https://github.com/mattn/jvgrep/tree/master/fastwalk

**Comment by eterps** [comment]
@mattn , thanks would love to see that.

**Comment by eterps** [comment]
:+1: thanks
