### ISSUE TITLE
Braced sections only work at the end of a pattern

### ISSUE THREAD

**Issue by rtpt-erikgeiser** [mattn/go-zglob#32]
Currently, intermediary braced sections cause the file walker to skip directories because the directory regular expression `dre` will contain the full path which does not match the intermediary directory.

### Example:
**File:** `foo/bar/baz`
**Glob:** `foo/{bar,x}/baz`

In this case the `dre` has the value `^foo/(bar|x)/baz` instead of the desired value `^foo/(bar|x)` so the file walker will skip the bar directory and `baz` will not be matched:

https://github.com/mattn/go-zglob/blob/ec22af56b6f3faf79c2afcb587d8d79a78878a42/zglob.go#L189-L191

The current tests only test trailing braced sections:

https://github.com/mattn/go-zglob/blob/ec22af56b6f3faf79c2afcb587d8d79a78878a42/zglob_test.go#L42-L43

**Comment by mattn** [comment]
Fixed in last change. But it still have problem that walk into useless matched.

**Comment by mattn** [comment]
Please file new issue if you still have problem. Thank you.
