### ISSUE TITLE
How does this compare to doublestar?

### ISSUE THREAD

**Issue by yuzhichang** [mattn/go-zglob#39]
[doublestar](https://github.com/bmatcuk/doublestar) 
- provides more APIs such as Match and PathMatch.
- doesn't use regexp at Glob.

I'm curious what's the performance difference.

**Comment by ghostsquad** [comment]
also curious

**Comment by mattn** [comment]
Sorry, get it your self please.

**Comment by ghostsquad** [comment]
Didn't mean any disrespect, I was just looking to know if there were features or functionality that was different. I'm not familiar with either project, they both look pretty good.

**Comment by mattn** [comment]
I understand it. you can find difference your self. :)
