### ISSUE TITLE
fastwalk sub package doesn't exist and is breaking this package

### ISSUE THREAD

**Issue by markbates** [mattn/go-zglob#6]
/Users/callen/src
~ go get -u github.com/gobuffalo/buffalo/buffalo
package github.com/mattn/go-zglob/fastwalk: cannot find package "github.com/mattn/go-zglob/fastwalk" in any of:
   /Users/callen/.gimme/versions/go1.7.1.darwin.amd64/src/github.com/mattn/go-zglob/fastwalk (from $GOROOT)
   /Users/callen/src/src/github.com/mattn/go-zglob/fastwalk (from $GOPATH)

Looks like https://github.com/mattn/go-zglob/commit/760b124c0122b6d6df6e29c8e4074ac84b831d20 is the culprit

**Comment by markbates** [comment]
@mattn this is breaking some of your other packages, can you please fix? `go get` is failing all over the place because of this. Thanks.

**Comment by mattn** [comment]
sorry.

**Comment by markbates** [comment]
Woot! Thanks!

**Comment by curtisallen** [comment]
Thanks!
